"""created user profile tables

Revision ID: 7ea0e71ad576
Revises: 075aa4531aa3
Create Date: 2023-06-20 11:20:22.779415

"""
from alembic import op
import sqlalchemy as sa
import os

environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '7ea0e71ad576'
down_revision = '075aa4531aa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_educations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=50), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(length=50), nullable=False),
    sa.Column('degree', sa.String(length=50), nullable=False),
    sa.Column('fromDate', sa.Date(), nullable=False),
    sa.Column('toDate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('fromDate', sa.Date(), nullable=False),
    sa.Column('toDate', sa.Date(), nullable=True),
    sa.Column('company', sa.String(length=50), nullable=False),
    sa.Column('experienceTitle', sa.String(length=50), nullable=False),
    sa.Column('experienceDetails', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    if environment == "production":
        op.execute(f"ALTER TABLE user_educations SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE user_experiences SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE user_skills SET SCHEMA {SCHEMA};")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_skills', schema=SCHEMA)
    op.drop_table('user_experiences', schema=SCHEMA)
    op.drop_table('user_educations', schema=SCHEMA)
    # ### end Alembic commands ###
